proxy:
  secretToken: "a8f24670768b4ec13770e938e94c2525a8bc80348c13729e464daab665e7a76f"
auth:
  type: ldap
  admin:
    access: true
    users:
      - admin
  ldap:
    server:
      address: ldap-service.default.svc.cluster.local
      port: 389
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: cn=admin,dc=example,dc=com
        password: admin
      templates:
        - 'cn={username},ou=People,dc=example,dc=com'
      user:
        searchBase: 'ou=People,dc=example,dc=com'
        escape: False
        attribute: 'uid'
        dnAttribute: 'uid'
singleuser:
  cpu:
    limit: .5
    guarantee: .5
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
    - display_name: "Learning Data Science"
      description: "Datascience Environment with Sample Notebooks"
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
  extraEnv:
    EDITOR: "vim"